services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: stock-control-web-dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app # Sincroniza código local com o container
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
    stdin_open: true
    tty: true
